config/routes.rb
Rails.application.routes.draw do
  
 
 
  def draw(routes_name)
    instance_eval(File.read(Rails.root.join("config/routes/#{routes_name}.rb")))
  end

  get "/", to: redirect("/volun")

  scope 'volun' do
    
    concern :recoverable do
      post :recover, on: :member
    end
  
    resources :massive_email_historics
    resources :massive_sms_historics
    resources :volun_exports do
      get :delete_modal, on: :member
      get :download, on: :member
    end

    resources :meetings, concerns: :recoverable
    resources :activities , concerns: :recoverable
    
    devise_for :users
    resources :links do
      post :target, on: :collection
    end
    
    resources :addresses do
      get 'bdc_search_towns', on: :collection
      get 'bdc_search_roads', on: :collection
      get 'bdc_search_road_numbers', on: :collection
      get 'bdc_get_district_borought', on: :collection
    end
    resources :entities, concerns: :recoverable do
      get :ent_password, as: 'ent_password', on: :member
      get :new_password, on: :member
      get :update_password, on: :member
    end
    resources :citizens, concerns: :recoverable do
      get :citizen_password, on: :member
      get :send_massive_sms, on: :collection
      post :post_send_massive_sms, on: :collection
      get :historic_massive_sms, on: :collection
      get :new_password, on: :member
      get :update_password, on: :member
      resources :citizen_services do
        get :question, on: :member
      end
      resources :citizen_trackings
    end
    resources :citizen_services, concerns: :recoverable do
      get :export_questions, on: :collection
      get :question, on: :member
      get :search, on: :collection
      get :search_district, on: :collection
      resources :citizen_service_trackings
    end

    resources :citizen_trackings, concerns: :recoverable
    resources :citizen_service_trackings, concerns: :recoverable
    
    
    draw :volunteer
    draw :project
    draw :maintenance
    draw :rt
    draw :pt
    draw :tracking
    draw :manage_digital
    
    get 'accept_unsubscribe' => 'volunteers#accept_unsubscribe', as: 'accept_unsubscribe'  
    get 'show_sms' => 'volunteers#show_sms', as: 'show_sms'
    get 'send_sms' => 'volunteers#send_sms', as: 'send_sms'
    get 'show_mail' => 'volunteers#show_mail', as: 'show_mail'
    get 'send_mail' => 'volunteers#send_mail', as: 'send_mail'
    get 'send_mail_dataset' => 'administrators#send_mail_dataset', as: 'send_mail_dataset'
    get 'show_questions_mail_path' => 'citizen_services#show_mail', as: 'show_questions_mail'
    post 'send_questions_mail_path' => 'citizen_services#send_mail', as: 'send_questions_mail'
    get 'export_all'=> 'volunteers#export_all', as: 'export_all' #MGC
    get 'maintenance' => 'welcome#maintenance', as: 'maintenance'
    get 'administration' => 'welcome#administration', as: 'administration'
    root 'welcome#index'
  end


  get '/ckeditor/pictures' => 'ckeditor/rails/pictures#index'
  post '/ckeditor/pictures' => 'ckeditor/rails/pictures#create'
  delete '/ckeditor/pictures/:id' => 'ckeditor/rails/pictures#destroy'
  get '/ckeditor/attachment_files' => 'ckeditor/rails/attachment_files#index'
  post '/ckeditor/attachment_files' => 'ckeditor/rails/attachment_files#create'
  delete '/ckeditor/attachment_files' => 'ckeditor/rails/attachment_files#create'

  Ckeditor::Rails::Engine.routes.draw do
    resources :pictures, only: [:index, :create, :destroy]
    resources :attachment_files, only: [:index, :create, :destroy]
  end
  
  mount LetterOpenerWeb::Engine, at: "/letter_opener" if Rails.env.development?
end

app/controllers/administration/audits_controller.rb
class Administration::AuditsController < ApplicationController
  load_and_authorize_resource
  respond_to :html, :js
  before_action :authorize
  
  def index
    params[:q] ||= Audit.includes(:user,:resource).preload(:user,:resource).ransack_default   

    if params[:q][:s].split(/ /)[0].to_s=="user_name"
      @search_q=@audits.includes(:user,:resource).preload(:user,:resource).joins("LEFT OUTER JOIN managers ON users.loggable_id = managers.id AND loggable_type='Manager'").joins("LEFT OUTER JOIN volunteers ON users.loggable_id = volunteers.id AND loggable_type='Volunteer'").joins("LEFT OUTER JOIN entities ON users.loggable_id = entities.id AND loggable_type='Entity'").select("audits.*,managers.name,managers.last_name,managers.last_name_alt,volunteers.name,entities.name,volunteers.last_name,volunteers.last_name_alt").search(params[:q])
      @unpaginated_audit = @search_q.result.order("CONCAT(CONCAT(managers.name,managers.last_name,managers.last_name_alt), entities.name, CONCAT(volunteers.name,volunteers.last_name,volunteers.last_name_alt)) #{params[:q][:s].split(/ /)[1]}")
    elsif params[:q][:s].split(/ /)[0].to_s=="resource"
      @search_q=@audits.includes(:user,:resource).preload(:user,:resource).joins(:resource).select("audits.*,resources.description").search(params[:q])
      @unpaginated_audit = @search_q.result.order("resources.description #{params[:q][:s].split(/ /)[1]}")
    elsif params[:q][:s].split(/ /)[0].to_s=="id"
      params[:q][:s] = "created_at desc"
      @search_q = @audits.includes(:user,:resource).preload(:user,:resource).search(params[:q])
      @search_q.sorts ||= 'created_at desc'
      @unpaginated_audit = @search_q.result.order("audits.created_at desc")
    else
      @search_q = @audits.includes(:user,:resource).preload(:user,:resource).search(params[:q])
      @search_q.sorts ||= 'created_at desc'
      @unpaginated_audit = @search_q.result.order("audits.created_at desc")
    end

    @unpaginated_audit=GlobalSearch.search_filter(@unpaginated_audit,
      [ ["ilike","audits.operation_type" , "#{params["search_operation"]}"],
        ["collective",[
          ["join",Audit.joins(:user).joins("LEFT OUTER JOIN entities ON users.loggable_id = entities.id AND loggable_type='Entity'"),"entities.name",:audits],
          ["join",Audit.joins(:user).joins("LEFT OUTER JOIN managers ON users.loggable_id = managers.id AND loggable_type='Manager'"),"managers.name",:audits],
          ["join",Audit.joins(:user).joins("LEFT OUTER JOIN managers ON users.loggable_id = managers.id AND loggable_type='Manager'"),"CONCAT(managers.name,' ',managers.last_name)",:audits],
          ["join",Audit.joins(:user).joins("LEFT OUTER JOIN managers ON users.loggable_id = managers.id AND loggable_type='Manager'"),"CONCAT(managers.name,' ',managers.last_name,' ',managers.last_name_alt)",:audits],
          ["join",Audit.joins(:user).joins("LEFT OUTER JOIN volunteers ON users.loggable_id = volunteers.id AND loggable_type='Volunteer'"),"volunteers.name",:audits],
          ["join",Audit.joins(:user).joins("LEFT OUTER JOIN volunteers ON users.loggable_id = volunteers.id AND loggable_type='Volunteer'"),"CONCAT(volunteers.name,' ',volunteers.last_name)",:audits],
          ["join",Audit.joins(:user).joins("LEFT OUTER JOIN volunteers ON users.loggable_id = volunteers.id AND loggable_type='Volunteer'"),"CONCAT(volunteers.name,' ',volunteers.last_name,' ',volunteers.last_name_alt)",:audits],
          ["join",Audit.joins(:resource).all,"resources.description",:audits],
          ["join",Audit.joins(:resource).all,"audits.operation",:audits],
          "audits.operation"
          ],params["enter_text"]
        ],
        ["f_between",:created_at,params["search_start_date"],params["search_end_date"]],
        ["join",Audit.joins(:user).all,"users.loggable_type",:audits,(params["search_type"] unless params["search_type"].to_s=="null")],
        ["join",Audit.joins(:user).joins("LEFT OUTER JOIN entities ON users.loggable_id = entities.id AND loggable_type='Entity'"),"entities.name",:audits,params["search_manager"]],
        ["join",Audit.joins(:user).joins("LEFT OUTER JOIN managers ON users.loggable_id = managers.id AND loggable_type='Manager'"),"CONCAT(managers.name,' ',managers.last_name,' ',managers.last_name_alt)",:audits,params["search_manager"]],
        ["join",Audit.joins(:user).joins("LEFT OUTER JOIN volunteers ON users.loggable_id = volunteers.id AND loggable_type='Volunteer'"),"CONCAT(volunteers.name,' ',volunteers.last_name,' ',volunteers.last_name_alt)",:audits,params["search_manager"]],
        ["join",Audit.joins(:resource).all,"resources.description",:audits,params["search_resource"]]
      ])
    if params["search_type"].to_s == "null"
      @unpaginated_audit=@unpaginated_audit.where("audits.user_id IS NULL")
    end
    @audits = @unpaginated_audit.paginate(page: params["page"], per_page: params["per_page"]||15)
   
    respond_with(@audits) do |format|
      format.csv { stream_csv_report(@unpaginated_audit,params)  }
    end
  rescue => e
    log_error("COD-00001",e) 
  end

  def show
    respond_with(@audit) do |format|
      format.html
    end
  rescue => e
    log_error("COD-00002",e) 
  end
  
  protected

  def get_model_class
    @model_class = Audit
  end
end

app/controllers/administration/catalogue/areas_controller.rb
class Administration::Catalogue::AreasController < ApplicationController
  load_and_authorize_resource
  respond_to :html, :js, :json
  before_action :authorize
  
  def index
    params[:q] ||= View::List::Area.ransack_default
    @search_q = View::List::Area.all.search(params[:q])
    @search_q.sorts ||= 'id asc'

    @unpaginated_areas = @search_q.result
    @unpaginated_areas = GlobalSearch.search_filter(@unpaginated_areas, [
        ["strict",:id,params["search_id"]],
        ["strict",:active,params["search_status"]],
        ["ilike",:name,params["search_nombre"]],
        ["collective",[ :id,:name ],params["enter_text"]]
      ])
    @areas = @unpaginated_areas.paginate(page: params["page"], per_page: params["per_page"]||15)
    
    respond_with(@areas, :location => administration_catalogue_areas_path)
  rescue => e
    log_error("COD-00001",e) 
  end

  def show
    respond_with(@area) do |format|
      format.js 
      format.html
    end
  rescue => e
    log_error("COD-00002",e) 
  end

  def new
    @area = Area.new
    respond_with(@area, :location => administration_catalogue_areas_path)
  rescue => e
    log_error("COD-00003",e) 
  end

  def edit
  rescue => e
    log_error("COD-00004",e) 
  end

  def create
    AuditGenerateHelper.audit_create(@area, current_user)
    respond_with(@area, :location => administration_catalogue_areas_path)
  rescue => e
    log_error("COD-00005",e) 
  end

  def update
    AuditGenerateHelper.audit_update(@area, area_params, current_user)
    respond_with(@area, :location => administration_catalogue_areas_path)
  rescue => e
    log_error("COD-00006",e) 
  end

  def destroy
    AuditGenerateHelper.audit_archive(@area, current_user)
    respond_with(@area, :location => administration_catalogue_areas_path)
  rescue => e
    log_error("COD-00007",e) 
  end

  def recover
    AuditGenerateHelper.audit_recover(@area, current_user)
    respond_with(@area, :location => administration_catalogue_areas_path)
  rescue => e
    log_error("COD-00008",e) 
  end
  
  protected

  def get_model_class
    @model_class = Area
  end

  def area_params
    params.require(:area).permit(:name, :description, :active)
  end
end

app/controllers/administration/catalogue/boroughts_controller.rb
class Administration::Catalogue::BoroughtsController < ApplicationController
    load_and_authorize_resource
    respond_to :html, :js, :json
    before_action :authorize
    
    def index
      params[:q] ||= View::List::Borought.ransack_default      
      @search_q = View::List::Borought.all.search(params[:q])
      @search_q.sorts ||= 'name asc'
  
      @unpaginated_boroughts = @search_q.result
      @unpaginated_boroughts =GlobalSearch.search_filter(@unpaginated_boroughts, [
          ["strict",:active,params["search_status"]],
          ["ilike",:name,params["search_nombre"]],
          ["collective",[ :id,:name ],params["enter_text"]]
        ])
      @boroughts = @unpaginated_boroughts.paginate(page: params["page"], per_page: params["per_page"]||15)
  
      respond_with(@boroughts, :location => administration_catalogue_boroughts_path)
    rescue => e
      log_error("COD-00001",e) 
    end
  
    def show
      respond_with(@borought) do |format|
        format.js
        format.html
      end
    rescue => e
      log_error("COD-00002",e) 
    end
  
    def new
      @borought = Borought.new
      respond_with(@borought, :location => administration_catalogue_boroughts_path)
    rescue => e
      log_error("COD-00003",e) 
    end
  
    def edit
    rescue => e
      log_error("COD-00004",e) 
    end
  
    def create
      AuditGenerateHelper.audit_create(@borought, current_user)
      respond_with(@borought, :location => administration_catalogue_boroughts_path)
    rescue => e
      log_error("COD-00005",e) 
    end
  
    def update
      AuditGenerateHelper.audit_update(@borought, borought_params, current_user)
      respond_with(@borought, :location => administration_catalogue_boroughts_path)
    rescue => e
      log_error("COD-00006",e) 
    end
  
    def destroy
      AuditGenerateHelper.audit_archive(@borought, current_user)
      respond_with(@borought, :location => administration_catalogue_boroughts_path)
    rescue => e
      log_error("COD-00007",e) 
    end
  
    def recover
      AuditGenerateHelper.audit_recover(@borought, current_user)
      respond_with(@borought, :location => administration_catalogue_boroughts_path)
    rescue => e
      log_error("COD-00008",e) 
    end
  
    protected
  
    def get_model_class
      @model_class = Borought
    end

    def borought_params
      params.require(:borought).permit(:name, :code, :district_id)
    end
end

app/controllers/administration/catalogue/channels_controller.rb
class Administration::Catalogue::ChannelsController < ApplicationController
  load_and_authorize_resource
  respond_to :html, :js, :json
  before_action :authorize
  
  def index
    params[:q] ||= View::List::Channel.ransack_default
    @search_q = View::List::Channel.all.search(params[:q])
    @search_q.sorts ||= 'id asc'

    @unpaginated_channels = @search_q.result
    @unpaginated_channels = GlobalSearch.search_filter(@unpaginated_channels, [
        ["strict",:id,params["search_id"]],
        ["strict",:active,params["search_status"]],
        ["ilike",:name,params["search_nombre"]],
        ["ilike",:code,params["search_code"]],
        ["collective",[ :id,:name,:code ],params["enter_text"]]
      ])
    @channels = @unpaginated_channels.paginate(page: params["page"], per_page: params["per_page"]||15)

    respond_with(@channels, :location => administration_catalogue_channels_path)
  rescue => e
    log_error("COD-00001",e) 
  end

  def show
    respond_with(@channel) do |format|
      format.js 
      format.html
    end
  rescue => e
    log_error("COD-00002",e) 
  end

  def new
    @channel = Channel.new
    respond_with(@channel, :location => administration_catalogue_channels_path)
  rescue => e
    log_error("COD-00003",e) 
  end

  def edit
  rescue => e
    log_error("COD-00004",e) 
  end

  def create
    AuditGenerateHelper.audit_create(@channel, current_user)
    respond_with(@channel, :location => administration_catalogue_channels_path)
  rescue => e
    log_error("COD-00005",e) 
  end

  def update
    AuditGenerateHelper.audit_update(@channel, channel_params, current_user)
    respond_with(@channel, :location => administration_catalogue_channels_path)
  rescue => e
    log_error("COD-00006",e) 
  end

  def destroy
    AuditGenerateHelper.audit_archive(@channel, current_user)
    respond_with(@channel, :location => administration_catalogue_channels_path)
  rescue => e
    log_error("COD-00007",e) 
  end

  def recover
    AuditGenerateHelper.audit_recover(@channel, current_user)
    respond_with(@channel, :location => administration_catalogue_channels_path)
  rescue => e
    log_error("COD-00008",e) 
  end
  
  protected

  def get_model_class
    @model_class = Channel
  end

  def channel_params
    params.require(:channel).permit(:name, :code, :active)
  end
end

app/views/administration/resources/_form.html.erb
<div class="well">
  <%= simple_form_for(@resource, as: :resource,method: method, url: path) do |f| %>

  <div class="form-inputs">
    <%= f.input :name %>
    <%= f.input :description %>
    <%= f.input :active %>
    <%= f.input :main if current_user.loggable.super_admin? %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
  <% end %>
</div>

app/views/administration/resources/_resource.html.erb
<tr id="<%= dom_id(resource) %>" >

  <% @model_class.public_send("#{current_user.loggable.role.kind}_columns").each do |attr_name| %>
    <td><%= show_attr(resource, attr_name) %></td>
  <% end %>

  <td class="index_table-actions">
    <%= link_to_show(resource, path: "administration_resource_path") %>
    <%= link_to_edit(resource, path: "edit_administration_resource_path") %>
<% if resource.try(:archived?) %>
    <%= link_to_recover(resource, path: "recover_administration_resource_path") %>
<% else %>
    <%= link_to_destroy(resource, path: "administration_resource_path") %>
<% end %>
  </td>
</tr>

app/views/administration/resources/_search.html.erb
<div class="row">
  <div class="col-md-12">
    <h2><%= t('search_filter')%></h2>
  </div>
</div>

<div class="index-panel row well">  
  <div class="col-md-12">
    <div class="row">
      <%= content_tag :label, t('resources_filter.data'), class: 'col-sm-9 control-label' %>
    </div>
    <div class="row">
        <%= text_field_tag :search_description, params["search_description"] ,placeholder: t('resources_filter.description'), class: 'form-control col-md-4',  style: 'width: 151px; margin:0px 2px;'%>
        <div class="col-md-2" style= 'width: 191px; margin:0px 2px;'>
          <div class="row">
            <%= text_field_tag :enter_text, params['enter_text'] ,placeholder: t('volunteer_filter.input_text'), class: 'form-control col' %>
            <div class="tooltip col">
              <%=fa_icon "question-circle" ,class: "fa-1x"%>
              <span class="tooltiptext"><%=model_class.tooltip%></span>
            </div>
          </div>
        </div>
        <%= text_field_tag :search_nombre, params["search_nombre"] ,placeholder: t('resources_filter.field_name'), class: 'form-control col-md-4',  style: 'width: 151px; margin:0px 2px;'%>
        <%= select_tag :search_status, options_for_select({ t('resources_filter.active') => true, t('resources_filter.inactive') => false, t('all')=>'' } ||{},params["search_status"]), include_blank: t('resources_filter.field_select_state'),
                class:     'form-control col-md-6',
                id:        'search_status-select',
                style:     'width:100px; margin:0px 2px;' %>
    </div>
  </div>
  
  <div class="col-sm-12 text-right" style="margin: 20px 0px 0px 0px;">
    <button type="button" name="button" class="btn btn-primary" id="buttonCleanResource"><%= t('reset_search') %></button>
    <button type="button" name="button" class="btn btn-success btn-default" id="buttonSearchResource"><%= t('search') %></button>
  </div>
</div>  

<div class="row">
  <div class="col">
    <%= content_tag(:div, link_to_new(model_class, path: "new_administration_resource_path"), class: 'pull-left') %>
  </div>
</div>
<script>

function push_enter(event){
    search_enter(event, search_js_resource);
}

    //$(document).on('keypress', push_enter);

    $('#buttonSearchResource').on('click', function() {
        search_js_resource();
    });

    $('#buttonCleanResource').on('click', function() {
        $(location).attr('href', "<%=administration_resources_url%>");
    });

    $('#pages-select').on('change', function() {
        search_js_resource();
    });
    
    $('#search_description').on('keyup', function() {
        correct_string($('#search_description'));
    });
    
    $('#enter_text').on('keyup', function() {
        correct_string($('#enter_text'));
    });

    $('#search_nombre').on('keyup', function() {
        correct_string($('#search_nombre'));
    });
    
</script>

app/views/administration/resources/_show.html.erb
<dl class="dl-horizontal">

  <dt><%= Resource.human_attribute_name(:id) %>:</dt>
  <dd><%= @resource.id %></dd>
  <dt><%= Resource.human_attribute_name(:name) %>:</dt>
  <dd><%= @resource.name %></dd>
  <dt><%= Resource.human_attribute_name(:description) %>:</dt>
  <dd><%= @resource.description %></dd>
  <dt><%= Resource.human_attribute_name(:active) %>:</dt>
  <dd><%= t("humanize.#{@resource.active}") %></dd>
  <dt><%= Resource.human_attribute_name(:created_at) %>:</dt>
  <dd><%= show_simple_date(@resource.created_at) %></dd>

</dl>

app/views/administration/resources/edit.html.erb
<%= main_title(t("action.edit", model: Resource.model_name.human)) %>

<div class="row">
  <div class="col-md-5">
    <%= render 'form', method: :put, path: administration_resource_path(@resource) %>
  </div>
</div>

<%= link_to( t('action.back'),administration_resources_path, class: 'btn btn-default') %>

app/views/administration/resources/index.html.erb
<%= render partial: "common/title", locals: {model_class: @model_class} %>
<%= render partial: "search", locals: {search: @search_q,model_class: @model_class} %>
<div id="recarga-filtros">
  <%= render partial: "shared/count", locals: {model_class: @model_class,count: @resources.count} %>
  <%= render partial: "common/generic_table", locals: {search: @search_q,collection: @resources, model_class: @model_class, partial: 'resource' } %>
  <%= render partial: "shared/pagination", locals: {collection: @resources, urlchange: "search_js_resource()"} %>
</div>
<div class="col-md-12">
  <div class="col-md-1">
    <%= button_to(t('action.back'), administration_path, method: :get)%>
  </div>
</div>

app/views/administration/resources/new.html.erb
<%= main_title(t("action.new", model: Resource.model_name.human)) %>

<div class="row">
  <div class="col-md-5">
    <%= render 'form', method: :post, path: administration_resources_path %>
  </div>
</div>

<%= link_to( t('action.back'),administration_resources_path, class: 'btn btn-default') %>

app/views/administration/resources/show.html.erb
<%= main_title(t("action.show", model: Resource.model_name.human)) %>

<%=render "show"%>
<% unless request.xhr? %>
<%= link_to( t('action.back'),administration_resources_path, class: 'btn btn-default') %>
<% end %>

app/views/administration/resources/show.js.erb
swal({width: 600, 
title: '<%= main_title(t("action.show", model: Resource.model_name.human)) %>',
html: '<%= j (render 'show') %>'})