config/routes.rb
Rails.application.routes.draw do
  
 
 
  def draw(routes_name)
    instance_eval(File.read(Rails.root.join("config/routes/#{routes_name}.rb")))
  end

  get "/", to: redirect("/volun")

  scope 'volun' do
    
    concern :recoverable do
      post :recover, on: :member
    end
  
    resources :massive_email_historics
    resources :massive_sms_historics
    resources :volun_exports do
      get :delete_modal, on: :member
      get :download, on: :member
    end

    resources :meetings, concerns: :recoverable
    resources :activities , concerns: :recoverable
    
    devise_for :users
    resources :links do
      post :target, on: :collection
    end
    
    resources :addresses do
      get 'bdc_search_towns', on: :collection
      get 'bdc_search_roads', on: :collection
      get 'bdc_search_road_numbers', on: :collection
      get 'bdc_get_district_borought', on: :collection
    end
    resources :entities, concerns: :recoverable do
      get :ent_password, as: 'ent_password', on: :member
      get :new_password, on: :member
      get :update_password, on: :member
    end
    resources :citizens, concerns: :recoverable do
      get :citizen_password, on: :member
      get :send_massive_sms, on: :collection
      post :post_send_massive_sms, on: :collection
      get :historic_massive_sms, on: :collection
      get :new_password, on: :member
      get :update_password, on: :member
      resources :citizen_services do
        get :question, on: :member
      end
      resources :citizen_trackings
    end
    resources :citizen_services, concerns: :recoverable do
      get :export_questions, on: :collection
      get :question, on: :member
      get :search, on: :collection
      get :search_district, on: :collection
      resources :citizen_service_trackings
    end

    resources :citizen_trackings, concerns: :recoverable
    resources :citizen_service_trackings, concerns: :recoverable
    
    
    draw :volunteer
    draw :project
    draw :maintenance
    draw :rt
    draw :pt
    draw :tracking
    draw :manage_digital
    
    get 'accept_unsubscribe' => 'volunteers#accept_unsubscribe', as: 'accept_unsubscribe'  
    get 'show_sms' => 'volunteers#show_sms', as: 'show_sms'
    get 'send_sms' => 'volunteers#send_sms', as: 'send_sms'
    get 'show_mail' => 'volunteers#show_mail', as: 'show_mail'
    get 'send_mail' => 'volunteers#send_mail', as: 'send_mail'
    get 'send_mail_dataset' => 'administrators#send_mail_dataset', as: 'send_mail_dataset'
    get 'show_questions_mail_path' => 'citizen_services#show_mail', as: 'show_questions_mail'
    post 'send_questions_mail_path' => 'citizen_services#send_mail', as: 'send_questions_mail'
    get 'export_all'=> 'volunteers#export_all', as: 'export_all' #MGC
    get 'maintenance' => 'welcome#maintenance', as: 'maintenance'
    get 'administration' => 'welcome#administration', as: 'administration'
    root 'welcome#index'
  end


  get '/ckeditor/pictures' => 'ckeditor/rails/pictures#index'
  post '/ckeditor/pictures' => 'ckeditor/rails/pictures#create'
  delete '/ckeditor/pictures/:id' => 'ckeditor/rails/pictures#destroy'
  get '/ckeditor/attachment_files' => 'ckeditor/rails/attachment_files#index'
  post '/ckeditor/attachment_files' => 'ckeditor/rails/attachment_files#create'
  delete '/ckeditor/attachment_files' => 'ckeditor/rails/attachment_files#create'

  Ckeditor::Rails::Engine.routes.draw do
    resources :pictures, only: [:index, :create, :destroy]
    resources :attachment_files, only: [:index, :create, :destroy]
  end
  
  mount LetterOpenerWeb::Engine, at: "/letter_opener" if Rails.env.development?
end

app/controllers/administration/catalogue/areas_controller.rb
class Administration::Catalogue::AreasController < ApplicationController
  load_and_authorize_resource
  respond_to :html, :js, :json
  before_action :authorize
  
  def index
    params[:q] ||= View::List::Area.ransack_default
    @search_q = View::List::Area.all.search(params[:q])
    @search_q.sorts ||= 'id asc'

    @unpaginated_areas = @search_q.result
    @unpaginated_areas = GlobalSearch.search_filter(@unpaginated_areas, [
        ["strict",:id,params["search_id"]],
        ["strict",:active,params["search_status"]],
        ["ilike",:name,params["search_nombre"]],
        ["collective",[ :id,:name ],params["enter_text"]]
      ])
    @areas = @unpaginated_areas.paginate(page: params["page"], per_page: params["per_page"]||15)
    
    respond_with(@areas, :location => administration_catalogue_areas_path)
  rescue => e
    log_error("COD-00001",e) 
  end

  def show
    respond_with(@area) do |format|
      format.js 
      format.html
    end
  rescue => e
    log_error("COD-00002",e) 
  end

  def new
    @area = Area.new
    respond_with(@area, :location => administration_catalogue_areas_path)
  rescue => e
    log_error("COD-00003",e) 
  end

  def edit
  rescue => e
    log_error("COD-00004",e) 
  end

  def create
    AuditGenerateHelper.audit_create(@area, current_user)
    respond_with(@area, :location => administration_catalogue_areas_path)
  rescue => e
    log_error("COD-00005",e) 
  end

  def update
    AuditGenerateHelper.audit_update(@area, area_params, current_user)
    respond_with(@area, :location => administration_catalogue_areas_path)
  rescue => e
    log_error("COD-00006",e) 
  end

  def destroy
    AuditGenerateHelper.audit_archive(@area, current_user)
    respond_with(@area, :location => administration_catalogue_areas_path)
  rescue => e
    log_error("COD-00007",e) 
  end

  def recover
    AuditGenerateHelper.audit_recover(@area, current_user)
    respond_with(@area, :location => administration_catalogue_areas_path)
  rescue => e
    log_error("COD-00008",e) 
  end
  
  protected

  def get_model_class
    @model_class = Area
  end

  def area_params
    params.require(:area).permit(:name, :description, :active)
  end
end

app/controllers/administration/catalogue/boroughts_controller.rb
class Administration::Catalogue::BoroughtsController < ApplicationController
    load_and_authorize_resource
    respond_to :html, :js, :json
    before_action :authorize
    
    def index
      params[:q] ||= View::List::Borought.ransack_default      
      @search_q = View::List::Borought.all.search(params[:q])
      @search_q.sorts ||= 'name asc'
  
      @unpaginated_boroughts = @search_q.result
      @unpaginated_boroughts =GlobalSearch.search_filter(@unpaginated_boroughts, [
          ["strict",:active,params["search_status"]],
          ["ilike",:name,params["search_nombre"]],
          ["collective",[ :id,:name ],params["enter_text"]]
        ])
      @boroughts = @unpaginated_boroughts.paginate(page: params["page"], per_page: params["per_page"]||15)
  
      respond_with(@boroughts, :location => administration_catalogue_boroughts_path)
    rescue => e
      log_error("COD-00001",e) 
    end
  
    def show
      respond_with(@borought) do |format|
        format.js
        format.html
      end
    rescue => e
      log_error("COD-00002",e) 
    end
  
    def new
      @borought = Borought.new
      respond_with(@borought, :location => administration_catalogue_boroughts_path)
    rescue => e
      log_error("COD-00003",e) 
    end
  
    def edit
    rescue => e
      log_error("COD-00004",e) 
    end
  
    def create
      AuditGenerateHelper.audit_create(@borought, current_user)
      respond_with(@borought, :location => administration_catalogue_boroughts_path)
    rescue => e
      log_error("COD-00005",e) 
    end
  
    def update
      AuditGenerateHelper.audit_update(@borought, borought_params, current_user)
      respond_with(@borought, :location => administration_catalogue_boroughts_path)
    rescue => e
      log_error("COD-00006",e) 
    end
  
    def destroy
      AuditGenerateHelper.audit_archive(@borought, current_user)
      respond_with(@borought, :location => administration_catalogue_boroughts_path)
    rescue => e
      log_error("COD-00007",e) 
    end
  
    def recover
      AuditGenerateHelper.audit_recover(@borought, current_user)
      respond_with(@borought, :location => administration_catalogue_boroughts_path)
    rescue => e
      log_error("COD-00008",e) 
    end
  
    protected
  
    def get_model_class
      @model_class = Borought
    end

    def borought_params
      params.require(:borought).permit(:name, :code, :district_id)
    end
end

app/controllers/administration/catalogue/channels_controller.rb
class Administration::Catalogue::ChannelsController < ApplicationController
  load_and_authorize_resource
  respond_to :html, :js, :json
  before_action :authorize
  
  def index
    params[:q] ||= View::List::Channel.ransack_default
    @search_q = View::List::Channel.all.search(params[:q])
    @search_q.sorts ||= 'id asc'

    @unpaginated_channels = @search_q.result
    @unpaginated_channels = GlobalSearch.search_filter(@unpaginated_channels, [
        ["strict",:id,params["search_id"]],
        ["strict",:active,params["search_status"]],
        ["ilike",:name,params["search_nombre"]],
        ["ilike",:code,params["search_code"]],
        ["collective",[ :id,:name,:code ],params["enter_text"]]
      ])
    @channels = @unpaginated_channels.paginate(page: params["page"], per_page: params["per_page"]||15)

    respond_with(@channels, :location => administration_catalogue_channels_path)
  rescue => e
    log_error("COD-00001",e) 
  end

  def show
    respond_with(@channel) do |format|
      format.js 
      format.html
    end
  rescue => e
    log_error("COD-00002",e) 
  end

  def new
    @channel = Channel.new
    respond_with(@channel, :location => administration_catalogue_channels_path)
  rescue => e
    log_error("COD-00003",e) 
  end

  def edit
  rescue => e
    log_error("COD-00004",e) 
  end

  def create
    AuditGenerateHelper.audit_create(@channel, current_user)
    respond_with(@channel, :location => administration_catalogue_channels_path)
  rescue => e
    log_error("COD-00005",e) 
  end

  def update
    AuditGenerateHelper.audit_update(@channel, channel_params, current_user)
    respond_with(@channel, :location => administration_catalogue_channels_path)
  rescue => e
    log_error("COD-00006",e) 
  end

  def destroy
    AuditGenerateHelper.audit_archive(@channel, current_user)
    respond_with(@channel, :location => administration_catalogue_channels_path)
  rescue => e
    log_error("COD-00007",e) 
  end

  def recover
    AuditGenerateHelper.audit_recover(@channel, current_user)
    respond_with(@channel, :location => administration_catalogue_channels_path)
  rescue => e
    log_error("COD-00008",e) 
  end
  
  protected

  def get_model_class
    @model_class = Channel
  end

  def channel_params
    params.require(:channel).permit(:name, :code, :active)
  end
end

app/controllers/administration/catalogue/collectives_controller.rb
class Administration::Catalogue::CollectivesController < ApplicationController
  load_and_authorize_resource
  respond_to :html, :js, :json
  before_action :authorize

  def index
    params[:q] ||= View::List::Collective.ransack_default  
    @search_q = View::List::Collective.all.search(params[:q])
    @search_q.sorts ||= 'name asc'

    @unpaginated_collectives = @search_q.result
    @unpaginated_collectives =GlobalSearch.search_filter(@unpaginated_collectives, [
        ["strict",:active,params["search_status"]],
        ["ilike",:name,params["search_nombre"]],
        ["ilike",:description,params["search_description"]],
        ["collective",[ :id,:name ],params["enter_text"]]
      ])
    @collectives = @unpaginated_collectives.paginate(page: params["page"], per_page: params["per_page"]||15)

    respond_with(@collectives, :location => administration_catalogue_collectives_path)
  rescue => e
    log_error("COD-00001",e)
  end

  def show
    respond_with(@collective) do |format|
      format.js
      format.html
    end
  rescue => e
    log_error("COD-00002",e)
  end

  def new
    @collective = Collective.new
    respond_with(@collective, :location => administration_catalogue_collectives_path)
  rescue => e
    log_error("COD-00003",e)
  end

  def edit
  rescue => e
    log_error("COD-00004",e)
  end

  def create
    AuditGenerateHelper.audit_create(@collective, current_user)
    respond_with(@collective, :location => administration_catalogue_collectives_path)
  rescue => e
    log_error("COD-00005",e)
  end

  def update
    AuditGenerateHelper.audit_update(@collective,collective_params, current_user)
    respond_with(@collective, :location => administration_catalogue_collectives_path)
  rescue => e
    log_error("COD-00006",e)
  end

  def destroy
    AuditGenerateHelper.audit_archive(@collective, current_user)
    respond_with(@collective, :location => administration_catalogue_collectives_path)
  rescue => e
    log_error("COD-00007",e)
  end

  def recover
    AuditGenerateHelper.audit_recover(@collective, current_user)
    respond_with(@collective, :location => administration_catalogue_collectives_path)
  rescue => e
    log_error("COD-00008",e)
  end

  protected

  def get_model_class
    @model_class = Collective
  end

  def collective_params
    params.require(:collective).permit(:name, :description, :active)
  end
end

app/controllers/administration/catalogue/coordinations_controller.rb
class Administration::Catalogue::CoordinationsController < ApplicationController
  load_and_authorize_resource
  respond_to :html, :js, :json
  before_action :authorize
  
  def index
    params[:q] ||= View::List::Coordination.ransack_default
    @search_q = View::List::Coordination.all.search(params[:q])
    @search_q.sorts ||= 'name asc'

    @unpaginated_coordinations = @search_q.result
    @unpaginated_coordinations =GlobalSearch.search_filter(@unpaginated_coordinations, [
        ["strict",:id,params["search_id"]],
        ["strict",:active,params["search_status"]],
        ["ilike",:name,params["search_nombre"]],
        ["collective",[ :id,:name ],params["enter_text"]]
      ])
    @coordinations = @unpaginated_coordinations.paginate(page: params["page"], per_page: params["per_page"]||15)

    respond_with(@coordinations, :location => administration_catalogue_coordinations_path)
  rescue => e
    log_error("COD-00001",e)
  end

  def show
    respond_with(@coordination) do |format|
      format.js
      format.html
    end
  rescue => e
    log_error("COD-00002",e)
  end

  def new
    @coordination = Coordination.new
    respond_with(@coordination, :location => administration_catalogue_coordinations_path)
  rescue => e
    log_error("COD-00003",e)
  end

  def edit
  rescue => e
    log_error("COD-00004",e)
  end

  def create
    AuditGenerateHelper.audit_create(@coordination, current_user)
    respond_with(@coordination, :location => administration_catalogue_coordinations_path)
  rescue => e
    log_error("COD-00005",e)
  end

  def update
    AuditGenerateHelper.audit_update(@coordination, coordination_params, current_user)
    respond_with(@coordination, :location => administration_catalogue_coordinations_path)
  rescue => e
    log_error("COD-00006",e)
  end

  def destroy
    AuditGenerateHelper.audit_archive(@coordination, current_user)
    respond_with(@coordination, :location => administration_catalogue_coordinations_path)
  rescue => e
    log_error("COD-00007",e)
  end

  def recover
    AuditGenerateHelper.audit_recover(@coordination, current_user)
    respond_with(@coordination, :location => administration_catalogue_coordinations_path)
  rescue => e
    log_error("COD-00008",e)
  end

  protected

  def get_model_class
    @model_class = Coordination
  end

  def coordination_params
    params.require(:coordination).permit(:name, :description, :active)
  end
end

app/controllers/administration/catalogue/genders_controller.rb
class Administration::Catalogue::GendersController < ApplicationController
  load_and_authorize_resource
  respond_to :html, :js, :json
  before_action :authorize
  
  def index
    params[:q] ||= View::List::Gender.ransack_default
    @search_q = View::List::Gender.all.search(params[:q])
    @search_q.sorts ||= 'name asc'

    @unpaginated_genders = @search_q.result
    @unpaginated_genders = GlobalSearch.search_filter(@unpaginated_genders, [
        ["strict",:active,params["search_status"]],
        ["ilike",:name,params["search_nombre"]],
        ["collective",[:id,:name],params["enter_text"]]
      ])
    @genders = @unpaginated_genders.paginate(page: params["page"], per_page: params["per_page"]||15)

    respond_with(@genders,:location => administration_catalogue_genders_path)
  rescue => e
    log_error("COD-00001",e) 
  end

  def show
    respond_with(@gender) do |format|
      format.js
      format.html
    end
  rescue => e
    log_error("COD-00002",e) 
  end

  def new
    @gender = Gender.new
    respond_with(@gender, :location => administration_catalogue_genders_path)
  rescue => e
    log_error("COD-00003",e) 
  end

  def edit
  rescue => e
    log_error("COD-00004",e) 
  end

  def create
    AuditGenerateHelper.audit_create(@gender, current_user)
    respond_with(@gender, :location => administration_catalogue_genders_path)
  rescue => e
    log_error("COD-00005",e) 
  end

  def update
    AuditGenerateHelper.audit_update(@gender, gender_params, current_user)
    respond_with(@gender, :location => administration_catalogue_genders_path)
  rescue => e
    log_error("COD-00006",e) 
  end

  def destroy
    AuditGenerateHelper.audit_archive(@gender, current_user)
    respond_with(@gender, :location => administration_catalogue_genders_path)
  rescue => e
    log_error("COD-00007",e) 
  end

  def recover
    AuditGenerateHelper.audit_recover(@gender, current_user)
    respond_with(@gender, :location => administration_catalogue_genders_path)
  rescue => e
    log_error("COD-00008",e) 
  end

  protected

  def get_model_class
    @model_class = Gender
  end

  def gender_params
    params.require(:gender).permit(:name, :active)
  end
end

app/views/administration/catalogue/volun_profiles/_form.html.erb
<div class="well">
  <%= simple_form_for(@volun_profile, as: :volun_profile,method: method, url: path) do |f| %>

    <div class="form-inputs">
      <%= f.input :name %>
      <%= f.input :active %>
    </div>

    <div class="form-actions">
      <%= f.button :submit %>
    </div>
  <% end %>
</div>

app/views/administration/catalogue/volun_profiles/_search.html.erb
<div class="container-fluid">
  <%=form_tag(administration_catalogue_volun_profiles_path, method: "get")  do %>
    <div class="row">
      <div class="col-md-12">
        <h2><%= t('search_filter')%></h2>
      </div>
    </div>
    <div class="index-panel row well">
      <div class="col-md-1">
        <%= label_tag :search_id,  t('volun_profile_filter.field_id'), class: 'control-label' %>
        <%= text_field_tag :search_id, params["search_id"] ,placeholder:  t('volun_profile_filter.field_id'), class: 'form-control'%>
      </div>   
      <div class="col-md-3">
        <%= label_tag :enter_text, t('volunteer_filter.input_text'), class: 'control-label' %>
        <div class="tooltip col">
          <%= fa_icon "question-circle" ,class: "fa-1x"%>
          <span class="tooltiptext"><%=model_class.tooltip%></span>
        </div>
        <%= text_field_tag :enter_text, params['enter_text'] ,placeholder: t('volunteer_filter.input_text'), class: 'form-control' %>
      </div>
      <div class="col-md-3">
        <%= label_tag :search_nombre, t('volun_profile_filter.field_name'), class: 'control-label' %>
        <%= text_field_tag :search_nombre, params["search_nombre"] ,placeholder: t('volun_profile_filter.field_name'), class: 'form-control'%>
      </div>      
      <div class="col-md-2">
        <%= label_tag :search_status, t('channel_filter.field_select_state'), class: 'control-label' %>
        <%= select_tag :search_status, options_for_select({ t('channel_filter.active') => true, t('channel_filter.inactive') => false, t('all')=>'' } ||{},params["search_status"]), include_blank: t('channel_filter.field_select_state'), class: 'form-control form-select'%>
      </div>     
      <div class="col-md-3" style="text-align: right;">
        <%=link_to "#{fa_icon "eraser" ,class: "fa-1x"} Limpiar búsqueda".html_safe, administration_catalogue_volun_profiles_path, class: "btn btn-primary", style: "margin-top: 2rem;"  %>
        <%=button_tag type: "submit",  class: "btn btn-success ", style: "margin-top: 2rem;" do  %>
          <%="#{fa_icon "search" ,class: "fa-1x"} Buscar".html_safe%>
        <%end%>
      </div>
    </div>
  <%end%>
  <div class="row">
    <div class="col">
      <%= content_tag(:div, link_to_new(model_class, path: "new_administration_catalogue_volun_profile_path"), class: 'pull-left')%>
    </div>
  </div>
  <%= render partial: "shared/count", locals: {count: @volun_profiles.count , model_class:  @model_class } %>
</div>

app/views/administration/catalogue/volun_profiles/_show.html.erb
<dl class="dl-horizontal">

  <dt><%= VolunProfile.human_attribute_name(:id) %>:</dt>
  <dd><%= @volun_profile.id %></dd>
  <dt><%= VolunProfile.human_attribute_name(:name) %>:</dt>
  <dd><%= @volun_profile.name %></dd>
  <dt><%= VolunProfile.human_attribute_name(:created_at) %>:</dt>
  <dd><%= show_simple_date(@volun_profile.created_at) %></dd>
  <dt><%= VolunProfile.human_attribute_name(:updated_at) %>:</dt>
  <dd><%= show_simple_date(@volun_profile.updated_at) %></dd>

</dl>

app/views/administration/catalogue/volun_profiles/_volun_profile.html.erb
<tr id="<%= dom_id(volun_profile) %>" >

  <% VolunProfile.main_columns.each do |attr_name| %>
    <td><%= show_attr(volun_profile, attr_name) %></td>
  <% end %>

  <td class="index_table-actions">
    <%= link_to_show(volun_profile, path: "administration_catalogue_volun_profile_path") %>
    <%= link_to_edit(volun_profile, path: "edit_administration_catalogue_volun_profile_path") %>
<% if volun_profile.try(:archived?) %>
    <%= link_to_recover(volun_profile, path: "recover_administration_catalogue_volun_profile_path") %>
<% else %>
    <%= link_to_destroy(volun_profile, path: "administration_catalogue_volun_profile_path") %>
<% end %>
  </td>
</tr>

app/views/administration/catalogue/volun_profiles/edit.html.erb
<%= main_title(t("action.edit", model: VolunProfile.model_name.human)) %>

<div class="row">
  <div class="col-md-5">
    <%= render 'form', method: :put, path: administration_catalogue_volun_profile_path(@volun_profile) %>
  </div>
</div>

<%= link_to( t('action.back'),administration_catalogue_volun_profiles_path, class: 'btn btn-default') %>

app/views/administration/catalogue/volun_profiles/index.html.erb
<%= render partial: "common/title", locals: {model_class: @model_class} %>
<%= render partial: "search", locals: {search: @volun_profiles,model_class: @model_class} %>
<%= render partial: "common/generic_table", locals: {search: @search_q,collection: @volun_profiles, model_class: @model_class, partial: 'volun_profile' } %>
<%= render partial: "shared/pagination", locals: {collection: @volun_profiles, urlchange: "search_js_volun_profiles()"} %>
<%=render partial: "common/button_back", locals: {path: maintenance_path, method: :get}%>

app/views/administration/catalogue/volun_profiles/new.html.erb
<%= main_title(t("action.new", model: VolunProfile.model_name.human)) %>

<div class="row">
  <div class="col-md-5">
    <%= render 'form',method: :post, path: administration_catalogue_volun_profiles_path %>
  </div>
</div>

<%= link_to( t('action.back'),administration_catalogue_volun_profiles_path, class: 'btn btn-default') %>

app/views/administration/catalogue/volun_profiles/show.html.erb
<%= main_title(t("action.show", model: VolunProfile.model_name.human)) %>

<%=render "show"%>
<% unless request.xhr? %>
<%= link_to( t('action.back'),administration_catalogue_volun_profiles_path, class: 'btn btn-default') %>
<% end %>

app/views/administration/catalogue/volun_profiles/show.js.erb
swal({width: 600, 
title: '<%= main_title(t("action.show", model: VolunProfile.model_name.human)) %>',
html: '<%= j (render 'show') %>'})